version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - '1080:1080'
  web:
    build: .
    command: bin/dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mailcatcher
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432
