version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - '1080:1080'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mailcatcher
      - redis
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432
  redis:
    image: redis:7.0
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
volumes:
  db-data:
